language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install nltk # install package + test dependencies
  - pip install pylint
  - pip install pytest-cov
script: pytest ; pylint asg3.py ; pytest --cov
after_success:
  - codecov # submit coverage